#!/usr/bin/env node
/**
 * Service Worker Build Script
 *
 * Compiles src/app/sw.ts to public/sw.js using esbuild.
 * Uses @serwist/build getManifest() for content-hashed precache entries.
 *
 * Run: node scripts/build-sw.mjs
 * Called automatically by: pnpm build
 */

import { build } from "esbuild";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import { existsSync } from "fs";
import { spawnSync } from "child_process";
import { randomUUID } from "crypto";
import { getManifest } from "@serwist/build";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = resolve(__dirname, "..");

// Configuration
const SW_SRC = resolve(projectRoot, "src/app/sw.ts");
const SW_DEST = resolve(projectRoot, "public/sw.js");

// Get git revision for dynamic page entries
function getGitRevision() {
  try {
    const result = spawnSync("git", ["rev-parse", "--short", "HEAD"], {
      encoding: "utf-8",
      cwd: projectRoot,
    });
    const revision = result.stdout?.trim();
    if (revision && revision.length > 0) return revision;
  } catch {
    // fall through to fallback
  }
  return randomUUID().slice(0, 8);
}

async function buildServiceWorker() {
  console.log("[@serwist/build] Building service worker...");

  if (!existsSync(SW_SRC)) {
    console.error(
      `[@serwist/build] Error: Service worker source not found at ${SW_SRC}`
    );
    process.exit(1);
  }

  const gitRevision = getGitRevision();

  // Generate content-hashed manifest from public assets
  const { manifestEntries, count, size } = await getManifest({
    globDirectory: resolve(projectRoot, "public"),
    globPatterns: ["**/*.{png,jpg,jpeg,webp,avif,svg,ico,woff,woff2}"],
    globIgnores: ["sw.js", "sw.js.map", "videos/**"],
    dontCacheBustURLsMatching: /\.[a-f0-9]{8,}\./,
    maximumFileSizeToCacheInBytes: 3 * 1024 * 1024,
    additionalPrecacheEntries: [
      { url: "/", revision: gitRevision },
      { url: "/menu", revision: gitRevision },
      { url: "/cart", revision: gitRevision },
      { url: "/offline", revision: gitRevision },
    ],
  });

  try {
    await build({
      entryPoints: [SW_SRC],
      outfile: SW_DEST,
      bundle: true,
      minify: process.env.NODE_ENV === "production",
      format: "iife",
      target: ["chrome90", "firefox90", "safari15"],
      define: {
        "self.__SW_MANIFEST": JSON.stringify(manifestEntries),
      },
      banner: {
        js: `// Generated by build-sw.mjs at ${new Date().toISOString()}\n// Entries: ${count} | Size: ${(size / 1024).toFixed(1)}KB\n`,
      },
    });

    console.log(`[@serwist/build] Service worker built successfully at ${SW_DEST}`);
    console.log(
      `[@serwist/build] Entries: ${count} | Total size: ${(size / 1024).toFixed(1)}KB | Git revision: ${gitRevision}`
    );
  } catch (error) {
    console.error("[@serwist/build] Error building service worker:", error);
    process.exit(1);
  }
}

buildServiceWorker();
