#!/usr/bin/env node
/**
 * Service Worker Build Script
 *
 * Compiles src/app/sw.ts to public/sw.js using esbuild.
 * This is a workaround for @serwist/next not supporting Turbopack in Next.js 16.
 *
 * Run: npx tsx scripts/build-sw.mjs
 * Called automatically by: pnpm build
 */

import { build } from "esbuild";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import { glob } from "glob";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = resolve(__dirname, "..");

// Configuration
const SW_SRC = resolve(projectRoot, "src/app/sw.ts");
const SW_DEST = resolve(projectRoot, "public/sw.js");
const PUBLIC_DIR = resolve(projectRoot, "public");
const NEXT_DIR = resolve(projectRoot, ".next");

// Generate precache manifest from build output
async function generatePrecacheManifest() {
  const entries = [];

  // Add key static assets from public folder
  const publicAssets = await glob("**/*.{js,css,png,jpg,jpeg,webp,avif,svg,ico,woff,woff2}", {
    cwd: PUBLIC_DIR,
    ignore: ["sw.js", "sw.js.map"],
  });

  for (const asset of publicAssets) {
    entries.push({
      url: `/${asset}`,
      revision: Date.now().toString(), // Simple revision based on build time
    });
  }

  // Add key pages for offline access
  const offlinePages = [
    "/",
    "/menu",
    "/cart",
  ];

  for (const page of offlinePages) {
    entries.push({
      url: page,
      revision: Date.now().toString(),
    });
  }

  return entries;
}

async function buildServiceWorker() {
  console.log("[@serwist/build] Building service worker...");

  // Check if source exists
  if (!existsSync(SW_SRC)) {
    console.error(`[@serwist/build] Error: Service worker source not found at ${SW_SRC}`);
    process.exit(1);
  }

  // Generate manifest
  const manifest = await generatePrecacheManifest();

  // Read the source file
  let swSource = readFileSync(SW_SRC, "utf-8");

  // Inject the manifest - replace self.__SW_MANIFEST with actual entries
  // This is a simplified approach; in production you'd want proper manifest injection
  const manifestCode = `self.__SW_MANIFEST = ${JSON.stringify(manifest)};`;

  try {
    // Build with esbuild
    await build({
      entryPoints: [SW_SRC],
      outfile: SW_DEST,
      bundle: true,
      minify: process.env.NODE_ENV === "production",
      format: "iife",
      target: ["chrome90", "firefox90", "safari15"],
      define: {
        "self.__SW_MANIFEST": JSON.stringify(manifest),
      },
      banner: {
        js: `// Generated by build-sw.mjs at ${new Date().toISOString()}\n`,
      },
    });

    // Inject manifest at the top of the built file
    const builtSw = readFileSync(SW_DEST, "utf-8");
    writeFileSync(SW_DEST, `${manifestCode}\n${builtSw}`);

    console.log(`[@serwist/build] Service worker built successfully at ${SW_DEST}`);
    console.log(`[@serwist/build] Precache entries: ${manifest.length}`);

  } catch (error) {
    console.error("[@serwist/build] Error building service worker:", error);
    process.exit(1);
  }
}

buildServiceWorker();
